[Don't review] Managed folder changes
GoogleCloudPlatform/gcsfuse pull request #1722
Opened 2024-02-16 09:09 UTC by Tulsishah

### Description

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - NA
2. Unit tests - NA
3. Integration tests - NA

2024-02-22 04:57 UTC, raj-prince commented on flags.go
> +				Name: "enable-managed-folders",
can we rename this flag to enable-managed-folders-listing?

As `enable-managed-folders`  feels like we are controlling the managed folder behavior which is not true.

2024-02-22 08:32 UTC, raj-prince commented on flags.go
> +				Usage: "GCSFuse automatically lists managed folders found within a bucket. " +
We can enhance the usage statement. We should also say about the `--implicit-dirs` flag something like - customer must pass `--implicit-dirs` flag to make this flag work for true value.

2024-02-22 08:46 UTC, raj-prince requested changes
Please incorporate.

2024-02-22 12:43 UTC, Tulsishah commented
> Please incorporate.

Done. PTAL

2024-02-23 06:39 UTC, raj-prince commented on internal/fs/fs.go
> +	// Setting this bool to false disables the visibility of empty managed folders.
I think, it's good to document clearly.

This flag is specially added to handle the corner case in listing managed folders. There are two corner cases (a) empty managed folder (b) nested managed folder which doesn't contain any descendent as object.  This flag always works in conjunction with `ImplicitDirectories` flag.

(a) If only `ImplicitDirectories` is true, all managed folders are listed other than above two mentioned case.
(b) If  both `ImplicitDirectories` and `EnableManagedFoldersListing` are true, then all the managed folders are listed including the above mentioned corner case.
(c) If `ImplicitDirectories` is false then no managed folders are listed irrespective of `EnableManagedFoldersListing` flag.

2024-02-23 06:42 UTC, raj-prince commented on internal/fs/inode/dir_test.go
> +func (t *DirTest) resetInode(implicitDirs bool, enableNonexistentTypeCache bool, enableManagedFolderListing bool) {
nit: enableManagedFolderListing -> enableManagedFoldersListing

2024-02-23 06:52 UTC, raj-prince commented on internal/fs/inode/dir_test.go
>  func (t *DirTest) LookUpChild_NonExistentTypeCache_ImplicitDirsDisabled() {
Can we also write a reasoning, why we haven't added unit test corresponding to added new flag in the dir_test.go?

2024-02-23 06:57 UTC, raj-prince commented on internal/fs/inode/dir.go
> +    enableManagedFoldersListing: enableManagedFoldersListing,
seems formatting issue.

2024-02-23 07:00 UTC, Tulsishah commented on internal/fs/inode/dir.go
> +    enableManagedFoldersListing: enableManagedFoldersListing,
This arise due to rebasing. Fixed

2024-02-23 11:51 UTC, raj-prince approved these changes

2024-02-23 11:52 UTC, merged