Upgrade github documentation to v2.0.0
GoogleCloudPlatform/gcsfuse pull request #1783
Opened 2024-03-12 04:05 UTC by gargnitingoogle

### Description

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - NA
2. Unit tests - NA
3. Integration tests - NA

2024-03-13 05:43 UTC, ashmeenkaur requested changes
Can you please pick up the changes from latest read cache release. I don't see min object changes in the semantics doc.

2024-03-13 06:05 UTC, gargnitingoogle commented
> Can you please pick up the changes from latest read cache release. I don't see min object changes in the semantics doc.

Good catch. I'll bring that in as well. Thanks @ashmeenkaur .

2024-03-13 12:04 UTC, sethiay commented on docs/semantics.md
> +**Important**: The rest of this document assumes that caching is disabled (by setting ```--stat-cache-ttl 0``` and ```--type-cache-ttl 0```). This is not the default. If you want the consistency guar
can we say by setting ```--stat-cache-ttl 0``` and ```--type-cache-ttl 0``` or ```metadata-cache:ttl-secs: 0``` ?

2024-03-13 13:30 UTC, gargnitingoogle commented on docs/semantics.md
> +**Important**: The rest of this document assumes that caching is disabled (by setting ```--stat-cache-ttl 0``` and ```--type-cache-ttl 0```). This is not the default. If you want the consistency guar
done

2024-03-15 13:17 UTC, sethiay approved these changes

2024-03-15 13:20 UTC, merged