Testing
GoogleCloudPlatform/gcsfuse pull request #1858
Opened 2024-04-23 04:48 UTC by Tulsishah

### Description

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - NA
2. Unit tests - NA
3. Integration tests - NA

2024-04-29 06:38 UTC, ashmeenkaur commented on tools/integration_tests/operations/copy_dir_test.go
> +	createDestNonEmptyDirectory(destDir, t)
Nit, can we merge line 252 and 253 into the same function. You can return dirPath from the create call for ease of readability

2024-04-29 07:30 UTC, ashmeenkaur commented on tools/integration_tests/util/setup/setup.go
> +func CreateTempFile(dirPath string) string {
Nit: There is a similar method in file_operations.go, shall we use it instead? I also think that we should pass filepath to this method as passing dirName is not very intuitive.

2024-04-30 04:30 UTC, ashmeenkaur commented on tools/integration_tests/operations/write_test.go
> +	const ContentType = "text/plain; charset=utf-8"
Why was this change required?

2024-04-30 04:48 UTC, Tulsishah commented on tools/integration_tests/operations/write_test.go
> +	const ContentType = "text/plain; charset=utf-8"
Accidentally introduced. Fixed

2024-04-30 05:17 UTC, ashmeenkaur commented on tools/integration_tests/operations/copy_dir_test.go
> -		return
h

2024-04-30 05:17 UTC, ashmeenkaur requested changes

2024-04-30 05:17 UTC, ashmeenkaur commented on tools/integration_tests/operations/copy_dir_test.go
> -func createSrcDirectoryWithObjects(dirPath string, t *testing.T) {
h

2024-04-30 07:28 UTC, ashmeenkaur approved these changes

2024-04-30 07:29 UTC, merged