Move from suite.suite to testing.T
GoogleCloudPlatform/gcsfuse pull request #2178
Opened 2024-07-16 11:33 UTC by sethiay

### Description
Move from suite.suite to testing.T as per best practices of writing tests.

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - NA
2. Unit tests - NA
3. Integration tests - NA

2024-07-16 17:33 UTC, kislaykishore requested changes

2024-07-16 17:33 UTC, kislaykishore commented on internal/cache/file/cache_handler_test.go
> +	InvalidateCacheTestFun := func(t *testing.T) {
This being an inner function should already have access to "t" from the outer scope. So, we probably don't need this parameter.

2024-07-17 05:39 UTC, sethiay commented on internal/cache/file/cache_handler_test.go
> -	_, err = file.Read(buf)
this is intended, we can skip this assertion.

2024-07-17 05:59 UTC, kislaykishore approved these changes

2024-07-17 05:59 UTC, kislaykishore commented on internal/cache/file/cache_handler_test.go
>  	file, err := os.OpenFile(downloadPath, os.O_RDONLY, 0600)
Should we close the file in the test?

2024-07-17 07:29 UTC, kislaykishore approved these changes

2024-07-17 07:46 UTC, ashmeenkaur approved these changes
Relying on @kislaykishore's review

2024-07-17 07:48 UTC, merged