[CLI Config Parity] Migrate Ignore Interrupts config and flag.
GoogleCloudPlatform/gcsfuse pull request #2340
Opened 2024-08-12 12:50 UTC by ashmeenkaur

### Description
This PR migrate Ignore Interrupts config and flag. Also added tests for file system config.
I will make kernel list cache migration changes in a follow up PR.

### Link to the issue in case of a bug fix.
NA

### Testing details
1. Manual - NA
2. Unit tests - Added
3. Integration tests - Via KOKORO

2024-08-12 13:11 UTC, kislaykishore requested changes

2024-08-12 13:11 UTC, kislaykishore commented on cmd/config_validation_test.go
> +					DirMode:                cfg.Octal(defaultDirMode),
Ditto for other cases
```suggestion
					DirMode:               0755,
```

2024-08-13 05:01 UTC, kislaykishore commented on cmd/config_validation_test.go
> +			name:       "Invalid value of ignore interrupts.",
Just checking if this was missed.

2024-08-13 06:20 UTC, ashmeenkaur commented on cmd/config_validation_test.go
> +			name:       "Invalid value of ignore interrupts.",
Done, sorry forgot to resolve.

2024-08-13 06:56 UTC, kislaykishore requested changes

2024-08-13 06:56 UTC, kislaykishore commented on cmd/root_test.go
> +	require.NoError(t, err)
```suggestion
```

2024-08-13 08:33 UTC, kislaykishore approved these changes

2024-08-13 08:46 UTC, merged