Mounting succeeds gcsbucket doesnot exist
GoogleCloudPlatform/gcsfuse pull request #779
Opened 2022-09-01 05:34 UTC by Tulsishah

Tried to solve an error Mounting succeeds even if gcs call fails.

2022-09-01 11:53 UTC, vadlakondaswetha requested changes
Please make changes in jacobsa/gcloud repo

2022-09-01 11:53 UTC, vadlakondaswetha commented on vendor/github.com/jacobsa/gcloud/gcs/conn.go
> +	//if typed, ok := err.(*googleapi.Error); ok {
please dont raise cls with commented code.

2022-09-01 11:53 UTC, vadlakondaswetha commented on vendor/github.com/jacobsa/gcloud/gcs/conn.go
> +		if strings.Contains(err.Error(), "Error 403") {
as discussed please dont use string comparision for error. cast it appropriately like this and compare the status code.
(err.(*fmt.wrapError).err).(*googleapi.Error).Code

2022-09-01 11:53 UTC, vadlakondaswetha commented on vendor/github.com/jacobsa/gcloud/gcs/conn.go
> +	"strings"
add unit tests

2022-09-01 11:53 UTC, raj-prince commented
Just for the information, this bug is similar to the issue open in the gcloud codebase: https://github.com/jacobsa/gcloud/issues/15

2022-09-01 11:57 UTC, vadlakondaswetha commented on vendor/github.com/jacobsa/gcloud/gcs/conn.go
> +		if strings.Contains(err.Error(), "Error 403") {
Also check if we can cast error as mentioned in the link Prince shared: https://github.com/jacobsa/gcloud/issues/15

2022-09-05 05:51 UTC, Tulsishah commented
raise the same PR on jacobsa/gcloud repo.

2022-09-05 05:51 UTC, closed without merging